### ISSUE TITLE
Mandarin speech editing test result bad

### ISSUE THREAD

**Issue by chenyang399** [WangHelin1997/SSR-Speech#10]
i did the Mandarin speech editing test 
i download the model in the huggingface, but the result is too bad, the edited region is meaningless speech

**Comment by WangHelin1997** [comment]
Hi! Please check the version of `espeak-ng` and `phonemizer` first. See [https://github.com/WangHelin1997/SSR-Speech/issues/5](https://github.com/WangHelin1997/SSR-Speech/issues/5)

**Comment by chenyang399** [comment]
已经改变了espaeak的版本为1.51和phonemize 版本是3.2.1 还是不行

**Comment by WangHelin1997** [comment]
可以提供您的测试sample吗
