### ISSUE TITLE
higher sampling rate

### ISSUE THREAD

**Issue by taalua** [WangHelin1997/SSR-Speech#11]
Thank you for excellent works.

For higher sampling rate, can I train audiocraft with higher max_sampling_rate, and 
use the ENCODEC_PATH to newly trained model? or architecture modification is necessary, thanks for the tip.

**Comment by WangHelin1997** [comment]
Hi,  thanks for your interest in our work!
You don't need to modify settings for training SSR-Speech models for a higher sampling rate, and the only thing is to retrain a codec model. And make sure to change the silence tokens during the inference according to the new codecs.
