### ISSUE TITLE
Popularity problem

### ISSUE THREAD

**Issue by yiwei0730** [WangHelin1997/SSR-Speech#12]
After reading the paper and some demos, I feel that it is not worse than Voice Craft. Why is the discussion popularity so low? Is there any hidden problem or is it a usage problem?

**Comment by WangHelin1997** [comment]
That's also what I want to figure out lol.

**Comment by yiwei0730** [comment]
are there models with both Chinese and English. I see that your HF only has separate models in Chinese and English.

**Comment by WangHelin1997** [comment]
Not trained yet.
