### ISSUE TITLE
How to generate zero shot speech without prompt transcription?

### ISSUE THREAD

**Issue by kdrkdrkdr** [WangHelin1997/SSR-Speech#2]
Thank you for your hard work.
Is there any example of inference with reference audio and without its transcription?

**Comment by WangHelin1997** [comment]
Hi, for the TTS, you could use an ASR model like Whisper to automatically get the transcript.
I am working on this script now.

**Comment by kdrkdrkdr** [comment]
Thank you for your reply. I would like to ask you one more question. Can it work in the case of cross-lingual?

**Comment by WangHelin1997** [comment]
Yes, we have trained the model on both English and Mandarin languages, and also a bilingual setting. That all works. I think it can fit more languages. What you need to do is preparing data and changing the phome set.

**Comment by WangHelin1997** [comment]
> Thank you for your hard work. Is there any example of inference with reference audio and without its transcription?

Done it
