### ISSUE TITLE
中文模型demo输出异常

### ISSUE THREAD

**Issue by gaosd** [WangHelin1997/SSR-Speech#5]
非常感谢您的开源！向您请教下中文模型的问题，在运行您的中文speech editing、tts 测试样例时，输出语音乱码，像是在说英语，附件为测试输出语音
[generated_.zip](https://github.com/user-attachments/files/17054401/generated_.zip)
执行命令：
`python inference_v2.py  \
    --seed 2024 \
    --sub_amount 0.12 \
    --aug_text \
    --use_watermark \
    --language 'zh' \
    --model_path "./pretrained_models/Mandarin.pth" \
    --codec_path "./pretrained_models/wmencodec.th" \
    --orig_audio "./demo/aishell3_test.wav" \
    --target_transcript "价格以基本都在一万到两万之间" \
    --temp_folder "./demo/temp" \
    --output_dir "./demo/generated_se" \
    --savename "aishell3_test" \
    --whisper_model_name "base"`

`python inference_v2.py  \
    --seed 2024 \
    --tts \
    --aug_text \
    --use_watermark \
    --language 'zh' \
    --model_path "./pretrained_models/Mandarin.pth" \
    --codec_path "./pretrained_models/wmencodec.th" \
    --orig_audio "./demo/aishell3_test.wav" \
    --prompt_length 3 \
    --target_transcript "我简直不敢相信同一个模型也可以进行文本到语音的合成" \
    --temp_folder "./demo/temp" \
    --output_dir "./demo/generated_tts" \
    --savename "aishell3_test" \
    --whisper_model_name "base"`

**Comment by WangHelin1997** [comment]
感谢您的关注和测试！
我这边测试没有发现问题，这是我测试的结果：
[demo_result.zip](https://github.com/user-attachments/files/17067352/demo_result.zip)

有几个问题：

1. 您下载和使用的模型是中文模型([https://huggingface.co/westbrook/SSR-Speech-Mandarin](https://huggingface.co/westbrook/SSR-Speech-Mandarin))吗?
2. 您可以重新clone repo试一下吗 （我最近每天都更新这个库）？

如果结果还不对，您可以check一下环境以及使用的gpu吗？欢迎反馈！～

**Comment by gaosd** [comment]
> 感谢您的关注和测试！ 我的颗粒测试没有发现问题，这是我测试的结果： [demo_result.zip](https://github.com/user-attachments/files/17067352/demo_result.zip)
> 
> 有几个问题：
> 
> 1. 您下载和使用的模型是中文模型（https://huggingface.co/westbrook/SSR-Speech-Mandarin）吗？
> 2. 您可以重新克隆仓库试一下吗（我最近每天都更新这个库）？
> 
> 如果结果不满意，您可以检查一下环境以及gpu的使用情况吗？欢迎反馈！～

感谢您的回复，定位到问题原因是不同版本的phonemize、espeak-ng转出来的音标不一致造成和您训练的模型无法对应。您能执行：phonemize --version  以提供您的版本信息吗，非常感谢！

**Comment by gaosd** [comment]
感谢，换用ubuntu22.04后解决。
espeak-ng的版本需要用1.50才能和模型对齐，如果不自己编译espeak-ng的话，需要用ubuntu22.04才能直接安装espeak-ng 1.50

**Comment by gaosd** [comment]
@WangHelin1997 注意到demo里的中文语音编辑结果，在开头位置插入的“食品”两字语速和句子整体是不一致的，请教下您针对此问题有可调节的参数嘛

**Comment by WangHelin1997** [comment]
> @WangHelin1997 注意到demo里的中文语音编辑结果，在开头位置插入的“食品”两字语速和句子整体是不一致的，请教下您针对此问题有可调节的参数嘛

您可以调节`cfg_coef`或者`sub_amount`， 语速问题请关注我们后续工作！
