### ISSUE TITLE
custom audio

### ISSUE THREAD

**Issue by AntroFyo** [WangHelin1997/SSR-Speech#7]
When i use custom chinese audio to test, there exit several problem.
Like ori trans is "本台消息 十一月三号 制定相关计划", target trans is "本台消息 二十一月三号 制定相关的计划",
this will lead to no change.  Is this correct?

**Comment by WangHelin1997** [comment]
Hi,

Thanks for your interest in our work!
Could you please provide the outputs of the running? Like your audio and the python outputs.

**Comment by AntroFyo** [comment]
like this. The true orig_spans, intervals and morphed_spans are correct. And i do not print them.

Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.2+cu118. Bad things might happen unless you revert torch to 1.x.
Suppressing numeral and symbol tokens: [3, 4, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 502, 568, 628, 805, 945, 1017, 1025, 1266, 1294, 1360, 1386, 1525, 1614, 1649, 1722, 1848, 1958, 2009, 2119, 2217, 2272, 2319, 2331, 2443, 2625, 2803, 2975, 3165, 3279, 3282, 3356, 3405, 3446, 3499, 3552, 3705, 4022, 4060, 4289, 4303, 4436, 4550, 4688, 4702, 4762, 4808, 5080, 5211, 5254, 5285, 5348, 5853, 5867, 5923, 6071, 6074, 6096, 6375, 6494, 6549, 6591, 6641, 6673, 6856, 6866, 6879, 6905, 6976, 7143, 7201, 7271, 7490, 7526, 7546, 7551, 7560, 7562, 7629, 7634, 7668, 7771, 7773, 7911, 7998, 8132, 8227, 8423, 8451, 8465, 8494, 8652, 8794, 8858, 8923, 9012, 9125, 9356, 9413, 9562, 9657, 9714, 9754, 10076, 10154, 10191, 10353, 10389, 10411, 10607, 10858, 10880, 11174, 11205, 11309, 11440, 11453, 11592, 11624, 11650, 11803, 11816, 11849, 11871, 11901, 11971, 12145, 12249, 12330, 12493, 12566, 12625, 12656, 12756, 12790, 12791, 12843, 12851, 12967, 13083, 13318, 13328, 13384, 13420, 13435, 13622, 13626, 13711, 13741, 13811, 13898, 13912, 14034, 14060, 14062, 14189, 14378, 14394, 14423, 14565, 14577, 14695, 14938, 15204, 15237, 15238, 15628, 15707, 15718, 15817, 16133, 16157, 16169, 16231, 16382, 16408, 16416, 16513, 16824, 16919, 16953, 17201, 17344, 17512, 17602, 17822, 17835, 17914, 18065, 18079, 18141, 18173, 18197, 18317, 18485, 18682, 18731, 19004, 19287, 19395, 19563, 19584, 19600, 19687, 19952, 19966, 20120, 20154, 20229, 20419, 20793, 20860, 20984, 21055, 21115, 21126, 21199, 21243, 21404, 21423, 21548, 21786, 21821, 21860, 22003, 22016, 22046, 22193, 22350, 22383, 22427, 22452, 22516, 22601, 22671, 22690, 22736, 22962, 23095, 23185, 23247, 23317, 23399, 23538, 23777, 23853, 23879, 23943, 23952, 24097, 24124, 24158, 24327, 24536, 24547, 24587, 24624, 24733, 25026, 25082, 25137, 25276, 25494, 25546, 25743, 26034, 26369, 26372, 26687, 26837, 26901, 27032, 27102, 27127, 27228, 27816, 27895, 27990, 28052, 28225, 28253, 28267, 28294, 28387, 28638, 28829, 28868, 28876, 28890, 28898, 28962, 29008, 29018, 29097, 29139, 29387, 29491, 29810, 29925, 29930, 29985, 30595, 30620, 30693, 30827, 30849, 30908, 30942, 30997, 31064, 31104, 31352, 31537, 31682, 31758, 31849, 31877, 32042, 32090, 32454, 32803, 32848, 32875, 32952, 33117, 33191, 33193, 33202, 33396, 33422, 33530, 33705, 33809, 33978, 34026, 34099, 34314, 34466, 34578, 35016, 35023, 35092, 35133, 35311, 35364, 36027, 36588, 36885, 37078, 37202, 37510, 37549, 37609, 37785, 38308, 38566, 38698, 38833, 38882, 38987, 39157, 39209, 39436, 39498, 40402, 40417, 40774, 40881, 41103, 41165, 41171, 41229, 41342, 41720, 41789, 42429, 42438, 42514, 42652, 42692, 42757, 43160, 43373, 43435, 43677, 44158, 44377, 44557, 44624, 45131, 45218, 45237, 45374, 45396, 45608, 45835, 45868, 45937, 46062, 46081, 46256, 46379, 46398, 46476, 46484, 46590, 46795, 46881, 47520, 47561, 47725, 47757, 48156, 48390, 48528, 48729, 48784, 48804, 48957, 49017, 49167, 49258, 50022]
It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.
It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.
本台消息 十一月三号 制定相关计划
本台消息 二十一月三号 制定相关的计划
ss============si==
orig_spans:  
intervals:  
morphed_spans:

**Comment by WangHelin1997** [comment]
Thanks! Could you also provide the audio for me to test?
