### ISSUE TITLE
15GiB+ memory requirement for inference

### ISSUE THREAD

**Issue by amssss0** [WangHelin1997/SSR-Speech#9]
First of all, thank you for open-sourcing it.

I tried it on Colab with a T4 GPU (15 GiB VRAM) for TTS, and I kept getting CUDA out-of-memory errors. The model seems quite large for TTS. I wanted to know if there are plans to release a quantized model that would require less VRAM?

**Comment by WangHelin1997** [comment]
Not yet. Feel free to contribute to this repo!
